avani.andon.web/Web/Controllers/PermissionController.cs
using System.Web.Mvc;
using System.Configuration;
using System;
using System.Collections.Generic;
using Model.DataModel;
using Model.Dao;
using Common;
using System.Linq;
using avSVAW.Controllers;

namespace avEMS.Controllers
{
    public class PermissionController : BaseController
    {
        string strConStr = ConfigurationManager.ConnectionStrings["ConStr"].ToString();

        //Permission by Group
        public ActionResult Index(string GroupID)
        {
            if (GroupID == null) GroupID = "0";

            int _groupId = int.Parse(GroupID);
            tblUserGroup userGroup = new UserGroupDao().ViewDetail(_groupId);

            int _customerId = (int)userGroup.CustomerId;
            string GroupName = userGroup.Name;

            string ControlerBack = "/Groups/Index";

            List<tblUserPermission> lstPer = new UserPermissionDao().findByGroupID(_groupId);
            //List<tblNode> lstNode = new NodeDao().ListAllByCustomerId(_customerId);
            List<tblLine> lstLine = new LineDao().ListAllByCustomer(_customerId);


            //ViewBag.lstNode = lstNode;
            ViewBag.lstLine = lstLine;

            //ViewBag.Permission = lstPer;
            ViewBag.ControlerBack = ControlerBack;
            ViewBag.ObjectId = _groupId;
            ViewBag.ObjectName = GroupName;

            return View("Index", lstPer);
        }
        [HttpPost]
        public ActionResult Save()
        {
            string[] keys = Request.Form.AllKeys;

            int GroupId = Convert.ToInt32(Request.Form["ObjectId"]);
            string keyV = "";
            string keyU = "";

            List<tblUserPermission> lstPer = new UserPermissionDao().findByGroupID(GroupId).Where(x => x.ObjectType != GlobalConstants.MENU_OBJECT_TYPE).ToList();

            foreach (tblUserPermission p in lstPer)
            {
                if (p.ObjectType == GlobalConstants.LINE_OBJECT_TYPE)
                {
                    keyV = "VZ_" + p.ObjectId;
                    keyU = "UZ_" + p.ObjectId;
                }

                if (p.ObjectType == GlobalConstants.NODE_OBJECT_TYPE)
                {
                    keyV = "VN_" + p.ObjectId;
                    keyU = "UN_" + p.ObjectId;
                }

                p.View = (Request.Form[keyV] == "1");
                p.Update = (Request.Form[keyU] == "1");

                new UserPermissionDao().Update(p);

            }
            return Redirect("/Permission/Index?GroupId=" + GroupId);
        }

        [HttpGet]
        public ActionResult Object(int ObjectId, int ObjectType)
        {
            //Chỗ này list ra hết các Group
            if (ObjectType == GlobalConstants.MENU_OBJECT_TYPE)
            {
                //Chỗ này chỉ Supper Admin mới có
                //Tạm bỏ qua
            }

            string ControlerBack = "";
            string ObjectName = "";

            tblUser tblUser = (Model.DataModel.tblUser)Session[GlobalConstants.USER_SESSION];
            int CustomerId = (int)tblUser.CustomerId;

            List<tblUserGroup> listGroups = new UserGroupDao().listAll(CustomerId);
            List<tblUserPermission> lstPer = new UserPermissionDao().findByObject(ObjectId, ObjectType);
            if (ObjectType == GlobalConstants.NODE_OBJECT_TYPE)
            {
                ControlerBack = "/Node/Index";
                ObjectName = new NodeDao().ViewDetail(ObjectId).Name;
            }

            if (ObjectType == GlobalConstants.LINE_OBJECT_TYPE)
            {
                ControlerBack = "/Line/Index";
                ObjectName = new LineDao().ViewDetail(ObjectId).Name;
            }

            ViewBag.Permission = lstPer;
            ViewBag.ObjectId = ObjectId;
            ViewBag.ObjectType = ObjectType;
            ViewBag.Name = ObjectName;

            ViewBag.ControlerBack = ControlerBack;
            return View("Object", listGroups);

        }

        [HttpPost]
        public ActionResult SaveObject()
        {
            string[] keys = Request.Form.AllKeys;
            int ObjectId = 0;
            int ObjectType = 0;

            ObjectId = Convert.ToInt32(Request.Form["ObjectId"]);
            ObjectType = Convert.ToInt32(Request.Form["ObjectType"]);

            //for (int i = 0; i < keys.Length; i++)
            //{
            //    if (keys[i].Contains("ObjectId"))
            //    {
            //    }

            //    if (keys[i].Contains("ObjectType"))
            //    {
            //    }

            //}
            string Param = "?ObjectId=" + ObjectId + "&ObjectType=" + ObjectType;

            List<tblUserPermission> lstPer = new UserPermissionDao().findByObject(ObjectId, ObjectType);

            foreach (tblUserPermission p in lstPer)
            {
                //bool CheckView = false;
                //bool CheckUpdate = false;

                string keyV = "V" + "_" + p.GroupId;
                string keyU = "U" + "_" + p.GroupId;

                p.View = (Request.Form[keyV] == "1");
                p.Update = (Request.Form[keyU] == "1");

                new UserPermissionDao().Update(p);

            }

            return Redirect("/Permission/PermissionByObject" + Param);
        }

    }
}

avani.andon.web/Web/Views/Permission/Index.cshtml
@model List<Model.DataModel.tblUserPermission>
@{
   @* ViewBag.Title = @Resources.Language.Permission + " [ " + Resources.Language.MenuGroup + "]: " + ViewBag.ObjectName;
    ViewBag.SubTitle = ViewBag.Title;*@
}
@section header{
    @ViewBag.SubTitle
}
<style>
    .old {
        background-color: #f9f9f9;
    }
</style>
<h3 style="margin-top: -10px;">@Resources.Language.Permission [@Resources.Language.MenuGroup ]: @ViewBag.ObjectName</h3>

<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm("Save", "Permission", FormMethod.Post, new { onsubmit = "return confirm('Bạn có muốn lưu lại thay đổi quyền này không?');", @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
        {
            <input type="hidden" name="ObjectID" value="@ViewBag.ObjectId" />
            <div class="box">
                <div class="box-header">
                    <div>
                        <a href="@ViewBag.ControlerBack" class="btn btn-default">
                            @Resources.Language.Back
                        </a>
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-save"></i>&nbsp; @Resources.Language.Save &nbsp;
                        </button>

                    </div>
                </div>
                <div class="box-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>@Resources.Language.Object</th>
                                <th>@Resources.Language.ObjectType</th>
                                <th>@Resources.Language.View</th>
                                <th>@Resources.Language.Edit</th>
                            </tr>
                        </thead>

                        @if (Model.Count > 0)
                        {
                            var i = 1;
                            var _ViewCheck = "";
                            var _UpdateCheck = "";
                            <tbody>
                                @if (ViewBag.lstLine.Count > 0)
                                {
                                    foreach (var z in ViewBag.lstLine)
                                    {
                                        //Kiểm tra quyền
                                        foreach (var per in Model)
                                        {

                                            if (per.ObjectId == z.Id && per.ObjectType == 1)
                                            {
                                                //Model.DataModel.tblUserPermission userPermission = ViewBag.Permission.lstPer.FirstOrDefault(x => x.GroupId == m.Id);
                                                _ViewCheck = ((bool)per.View) ? "checked" : "";
                                                _UpdateCheck = ((bool)per.Update) ? "checked" : "";
                                                break;
                                            }
                                        }
                                        <tr class="old">
                                            <td>@i</td>
                                            <td><b> @z.Name </b></td>
                                            <td>@Resources.Language.Line</td>
                                            <td><input type="checkbox" name="VZ_@z.Id" value="1" @_ViewCheck class="viewmenu  V chk isParent VZ_@z.Id" id="VZ_@z.Id" data-type="Z" data-id="@z.Id"></td>
                                            <td><input type="checkbox" name="UZ_@z.Id" value="1" @_UpdateCheck class="updatemenu  U chk isParent UZ_@z.Id" id="UZ_@z.Id" data-type="Z" data-id="@z.Id"></td>
                                        </tr>
                                        i++;


                                    }
                                }
                            </tbody>
                        }
                    </table>
                </div>
            </div>
        }
    </div>
</div>
@section Scripts{
    <script>
        $(document).ready(function () {


            $('input[type="checkbox"]').change(function () {
                if ($(this).hasClass('checkall')) {
                    $("." + $(this).attr('data-id')).prop('checked', this.checked);
                }
                if ($(this).hasClass('isParent')) {
                    if ($(this).hasClass('U')) {
                        $(".U" + $(this).attr('data-Type') + "_" + $(this).attr('data-id')).prop('checked', this.checked);
                    }
                    if ($(this).hasClass('V')) {
                        $(".V" + $(this).attr('data-Type') + "_" + $(this).attr('data-id')).prop('checked', this.checked);
                    }
                }
            })
        })
    </script>
}

avani.andon.web/Web/Views/Permission/Object.cshtml
@model List<Model.DataModel.tblUserGroup>
@{
    string strType = Resources.Language.Node;
    if (ViewBag.ObjectType == 1) { strType = Resources.Language.Zone; }
    ViewBag.Title = Resources.Language.Permission + " [" + strType + "]: " + ViewBag.Name;
    ViewBag.SubTitle = ViewBag.Title;
    string ux = "U" + ViewBag.Typestr;
    string vx = "V" + ViewBag.Typestr;
}
@section header{
    @ViewBag.SubTitle
}
<style>
    .old {
        background-color: #f9f9f9;
    }
</style>
@*@Styles.Render("~/AdminLTE/plugins/datatables/css")*@

<div class="row">
    <div class="col-xs-12">
        @using (Html.BeginForm("SaveObject", "Permission", FormMethod.Post, new { onsubmit = "return confirm('Are you sure to save these changes?');", @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
        {
            <input type="hidden" name="ObjectType" value="@ViewBag.ObjectType" />
            <input type="hidden" name="ObjectId" value="@ViewBag.ObjectId" />
            <div class="box">
                <div class="box-header">
                    <div style="float:right;">
                        <button type="submit" class="btn btn-success">
                            <i class="fa fa-file-o"></i>&nbsp; @Resources.Language.Save &nbsp;
                        </button>
                        <a href="@ViewBag.ControlerBack" class="btn btn-default">
                            <i class="fa fa-file-o"></i>&nbsp; @Resources.Language.Back &nbsp;
                        </a>
                    </div>
                </div>


                <div class="box-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>@Resources.Language.MenuGroup</th>
                                <th>@Resources.Language.View</th>
                                <th>@Resources.Language.Edit</th>
                            </tr>
                        </thead>

                        @if (Model.Count > 0)
                        {

                            var i = 1;

                            <tbody>

                                <tr style="background-color:#CCC;">
                                    <td colspan="2"><b>@Resources.Language.All</b></td>
                                    <td><input type="checkbox" class="checkall chk" data-id="menuV"></td>
                                    <td><input type="checkbox" class="checkall chk" data-id="menuU"></td>
                                </tr>

                                @foreach (var m in Model)
                                {
                                    var _ViewCheck = "";
                                    var _UpdateCheck = "";

                                    foreach (var per in ViewBag.Permission)
                                    {
                                        if (per.GroupId == m.Id)
                                        {
                                            //Model.DataModel.tblUserPermission userPermission = ViewBag.Permission.lstPer.FirstOrDefault(x => x.GroupId == m.Id);
                                            _ViewCheck = ((bool)per.View) ? "checked" : "";
                                            _UpdateCheck = ((bool)per.Update) ? "checked" : "";
                                            break;
                                        }
                                    }

                                    <tr>
                                        <td>@i</td>
                                        <td>
                                            <span>@m.Name</span>
                                        </td>
                                        <td><input type="checkbox" name="V_@m.Id" value="1" @_ViewCheck class="viewmenu menuV V chk" id="V_@m.Id" data-type="M" data-id="@m.Id"></td>
                                        <td><input type="checkbox" name="U_@m.Id" value="1" @_UpdateCheck class="updatemenu menuU U chk" id="U_@m.Id" data-type="M" data-id="@m.Id"></td>
                                    </tr>

                                    i++;
                                }






                            </tbody>
                        }
                    </table>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {

			$('input[type="checkbox"]').change(function(){
				if($(this).hasClass('checkall')){
					$("."+$(this).attr('data-id')).prop('checked',this.checked);
				}
				if($(this).hasClass('isParent')){
					if($(this).hasClass('U')){
						$(".U"+$(this).attr('data-Type')+"_"+$(this).attr('data-id')).prop('checked',this.checked);
					}
					if($(this).hasClass('V')){
						$(".V"+$(this).attr('data-Type')+"_"+$(this).attr('data-id')).prop('checked',this.checked);
					}
				}
			})
        })
    </script>
}