avani.andon.web/Web/Models/LineForm.cs
using Model.Dao;
using Model.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace avSVAW.Models
{
    public class LineForm : tblLine
    {
        public List<SelectListItem> Factories { get; set; }
        public List<SelectListItem> IsAutos { get; set; }
        public string FactoryName { get; set; }
        public long Create()
        {
            LineDao nodeDao = new LineDao();
            return nodeDao.Insert(Cast());
        }

        public void Update()
        {
            LineDao nodeDao = new LineDao();
            nodeDao.Update(Cast());
        }

        public void Cast(tblLine node)
        {
            this.Id = node.Id;
            this.Name = node.Name;
            this.Description = node.Description;
            this.Code = node.Code;
            this.FactoryId = node.FactoryId;
            this.nOrder = node.nOrder;
            this.IsAuto = node.IsAuto;
            this.FactoryName = new FactoryDao().GettblFactoryNameById(node.FactoryId);
        }
        public tblLine Cast()
        {
            return new tblLine()
            {
                Id = this.Id,
                Name = this.Name,
                Description = this.Description,
                Code = this.Code,
                FactoryId = this.FactoryId,
                nOrder = this.nOrder,
                IsAuto = this.IsAuto
            };
        }
    }
}

avani.andon.web/Web/Controllers/LineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using Common;
using Model.Dao;
using Model.DataModel;
using avSVAW.Common;
using avSVAW.Models;
using avSVAW.App_Start;

namespace avSVAW.Controllers
{
    public class LineController : BaseController
    {

        // GET: EventDef
        /// <summary>  
        /// First Action method called when page loads  
        /// Fetch all the rows from DB and display it  
        /// </summary>  
        /// <returns>Home View</returns>  
        public ActionResult Index()
        {
            List<tblLine> lst = new LineDao().listAll();
            List<LineForm> model = new List<LineForm>();
            foreach (tblLine l in lst)
            {
                LineForm lf = new LineForm();
                lf.Cast(l);
                model.Add(lf);
            }
            return View("Index", model);
        }

        /// <summary>  
        /// Action method, called when the "Add New Record" link clicked  
        /// </summary>  
        /// <returns>Create View</returns>  
        public ActionResult Create()
        {
            LineForm model = new LineForm();
            model.Factories = new FactoryDao().listAll().Select(n =>
                new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Name
                }).ToList();
            model.IsAutos = new List<SelectListItem>();
            model.IsAutos.Add(new SelectListItem() { Value = "false", Text = "Thủ công" });
            model.IsAutos.Add(new SelectListItem() { Value = "true", Text = "Tự động" });
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(LineForm model)
        {
            if (ModelState.IsValid)
            {
                tblLine l = model.Cast();

                new LineDao().Insert(l);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int Id)
        {
            tblLine l = new LineDao().ViewDetail(Id);
            LineForm model = new LineForm();
            model.Cast(l);
            model.Factories = new FactoryDao().listAll().Select(n =>
                new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Name
                }).ToList();
            model.IsAutos = new List<SelectListItem>();
            model.IsAutos.Add(new SelectListItem() { Value = "false", Text = "Thủ công" });
            model.IsAutos.Add(new SelectListItem() { Value = "true", Text = "Tự động" });
            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(LineForm model)
        {
            tblLine l = model.Cast();
            new LineDao().Update(l);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int Id)
        {
            new LineDao().Delete(Id);
            return RedirectToAction("Index");
        }


        [WebMethod]
        public JsonResult GetEventDefJsonList()
        {
            List<tblLine> lst = new LineDao().listAll();
            return Json(lst);
        }
    }
}

avani.andon.web/Web/Views/Line/Create.cshtml
@model avSVAW.Models.LineForm

<h3 id="dstitle" style="margin-top: -10px;">@Resources.Language.Create @Resources.Language.Line</h3>
<div class="row">
    <div class="col-xs-12">

        <div class="box">

            @using (Html.BeginForm("Create", "Line", FormMethod.Post, new { @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
            {

                <div class="box-body">

                    <input type="hidden" name="Id" class="form-control" value="@Model.Id" />

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Name, Resources.Language.Name, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Code, Resources.Language.Code, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Code, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.nOrder, Resources.Language.Order, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.nOrder, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.nOrder, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Description, Resources.Language.Description, new { @class = "control-label" })
                        </div>
                        <div class="col-md-10 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.FactoryId, Resources.Language.Factory, new { @class = "control-label" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.DropDownListFor(model => model.FactoryId, Model.Factories, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.FactoryId, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.IsAuto, "Cấu hình", new { @class = "control-label" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.DropDownListFor(model => model.IsAuto, Model.IsAutos, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.IsAuto, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-6">
                            <a href="/Line/Index">
                                <button class="btn btn-default" type="button">@Resources.Language.Back</button>
                            </a>
                            <button type="submit" class="btn btn-success">@Resources.Language.Save</button>&nbsp;
                        </div>
                    </div>
                </div>
            }

        </div>

    </div>
</div>

@section Scripts {
    @*<script src="~/assets/js/order.js"></script>*@
    <script src="~/assets/js/jquery.validate.js"></script>



    <script type="text/javascript">


        $(document).ready(function () {
            $('#frmValidate').validate({ // initialize the plugin
                rules: {
                    Name: {
                        required: true
                    }, Code: {
                        required: true
                    },
                    nOrder: {
                        required: true,
                        number: true
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
}

avani.andon.web/Web/Views/Line/Edit.cshtml
@model avSVAW.Models.LineForm
@{

    ViewBag.Title = Resources.Language.Line;
    ViewBag.SubTitle = Resources.Language.Edit + " " + ViewBag.Title;
}
@*@section header{

    }*@
<h3 id="dstitle" style="margin-top: -10px;">@ViewBag.SubTitle</h3>
@section Styles{
    <style>

        /* Create a custom checkbox */
        .av-checkbox {
            height: 25px;
            width: 25px;
            /*background-color: #eee;*/
        }
    </style>

}

@section Scripts{
    <script>
        //add css for attach file element
        var input = $("input:file").css({
            width: "100%",
            border: "0.1px solid"
        });
    </script>
    <script src="~/assets/js/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            $('#frmValidate').validate({ // initialize the plugin
                rules: {
                    Name: {
                        required: true
                    }, Code: {
                        required: true
                    },
                    nOrder: {
                        required: true,
                        number: true
                    }
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        })

    </script>
}


<div class="row">
    <div class="col-xs-12">

        <div class="box">
            @using (Html.BeginForm("Edit", "Line", FormMethod.Post, new { @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
            {
                <div class="box-body">
                    <input type="hidden" name="Id" class="form-control" value="@Model.Id" />
                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Code, Resources.Language.Code, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Code, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Name, Resources.Language.Name, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.nOrder, Resources.Language.Order, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.nOrder, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.nOrder, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Description, Resources.Language.Description, new { @class = "control-label" })
                        </div>
                        <div class="col-md-10 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.FactoryId, Resources.Language.Factory, new { @class = "control-label" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.DropDownListFor(model => model.FactoryId, Model.Factories, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.FactoryId, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.IsAuto, "Cấu hình", new { @class = "control-label" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.DropDownListFor(model => model.IsAuto, Model.IsAutos, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.IsAuto, "", new { @class = "text-danger" })

                    </div>

                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-6">
                            <a href="/Line/Index">
                                <button class="btn btn-default" type="button">@Resources.Language.Back</button>
                            </a>
                            <button type="submit" class="btn btn-success">@Resources.Language.Save</button>&nbsp;
                        </div>
                    </div>
                    <!-- /.box-footer -->
                </div>
            }

        </div>

    </div>
</div>

avani.andon.web/Web/Views/Line/Index.cshtml
@model List<avSVAW.Models.LineForm>
@{
    @*ViewBag.Title = Resources.Language.Line;
        ViewBag.SubTitle = Resources.Language.List + " " + Resources.Language.Line;*@
}
@section header{
    @ViewBag.SubTitle
}

<h3 style="margin-top: -10px;">@Resources.Language.List @Resources.Language.Line</h3>


<div class="row">
    <div class="col-xs-12">

        <div class="box">
            <!--<div class="box-header">
            <div style="float:right;">-->
            @*                        @Html.ActionLink("Add New Record", "Insert", null, new { @class = "btn btn-success" })*@
            <!--<a href="@Url.Action("Create")" class="btn btn-success">
                        <i class="fa fa-file-o"></i>&nbsp; @Resources.Language.Create &nbsp;
                    </a>
                </div>
            </div>-->
            <div class="box-header">
                <div>
                    <a href="@Url.Action("Create")" class="btn btn-success">
                        <i class="fa fa-plus-circle"></i>&nbsp; @Resources.Language.Create &nbsp;
                    </a>
                </div>
            </div>

            <div class="box-body">
                <table id="EventDeflist" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>@Resources.Language.Name</th>
                            <th>@Resources.Language.Code</th>
                            <th>@Resources.Language.Description</th>
                            <th>@Resources.Language.Factory</th>
                            <th>Cấu hình</th>
                            <th style="width: 20%">@Resources.Language.Action</th>
                        </tr>
                    </thead>
                    @if (Model.Count > 0)
                    {
                        var i = 1;
                        <tbody>
                            @foreach (var f in Model)
                            {
                                var config = f.IsAuto == false ? "Thủ công" : "Tự động";
                                <tr>
                                    <td>
                                        @i
                                    </td>
                                    <td>
                                        @f.Name
                                    </td>
                                    <td>@f.Code</td>
                                    <td>@f.Description </td>
                                    <td>@f.FactoryName </td>
                                    <td>@config</td>
                                    <td>
                                        <a href="/Line/Edit/@f.Id" class="btn btn-primary  btn-xs">
                                            <i class="fa fa-pencil"></i>&nbsp; @Resources.Language.Edit &nbsp;&nbsp;
                                        </a>
                                        &nbsp;
                                        <a href="/Line/Delete/@f.Id" class="btn btn-danger  btn-xs" onclick="return confirm('@Resources.Language.DeleteConfirm')">
                                            <i class="fa fa-trash"></i> &nbsp;@Resources.Language.Delete&nbsp;&nbsp;
                                        </a>
                                    </td>
                                </tr>
                                i = i + 1;
                            }
                        </tbody>
                    }

                </table>
            </div>
        </div>

    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#EventDeflist').DataTable({
                'paging': false,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': false,
                'autoWidth': false
            })

            $("#modalImport").click(function () {
                $("#importcsv").modal('show');
            });
        });
    </script>
}