avani.andon.web/Web/Models/NodeForm.cs
using Model.Dao;
using Model.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace avSVAW.Models
{
    public class NodeForm : tblNode
    {
        public List<SelectListItem> Lines { get; set; }
        public string LineName { get; set; }
        public List<SelectListItem> Zones { get; set; }
        public string ZoneName { get; set; }
        public List<SelectListItem> NodeTypes { get; set; }
        public string NodeTypeName { get; set; }
        public long Create()
        {
            NodeDao nodeDao = new NodeDao();
            return nodeDao.Insert(Cast());
        }

        public void Update()
        {
            NodeDao nodeDao = new NodeDao();
            nodeDao.Update(Cast());
        }

        public void Cast(tblNode node)
        {
            this.Id = node.Id;
            this.Name = node.Name;
            this.Description = node.Description;
            this.Active = node.Active;
            this.LineId = node.LineId;
            //this.rId = node.rId;
            this.LineName = new LineDao().GettblLineNameById(node.LineId);
            this.ZoneId = node.ZoneId;
            //this.ZoneName = new ZoneDao().GettblZoneNameById(node.ZoneId);
            this.nOrder = node.nOrder;

        }
        public tblNode Cast()
        {
            return new tblNode()
            {
                Id = this.Id,
                Name = this.Name,
                Description = this.Description,
                Active = this.Active,
                LineId = this.LineId,
                //rId=this.rId,
                ZoneId = this.ZoneId,
                //NodeTypeId = this.NodeTypeId,
                nOrder = this.nOrder
            };
        }
        public tblNode GetBaseNode(NodeForm nodeForm)
        {
            tblNode node = new tblNode();
            node.Id = nodeForm.Id;
            node.Name = nodeForm.Name;
            node.Active = nodeForm.Active;
            node.Description = nodeForm.Description;
            node.LineId = nodeForm.LineId;
            node.NodeTypeId = nodeForm.NodeTypeId;
            node.nOrder = nodeForm.nOrder;
            node.ZoneId = nodeForm.ZoneId;
            return node;
        }
    }
    public class NodeEventForm /*: tblNodeEvent*/
    {
        public string strStartDate { get; set; }
        public string strFromDate { get; set; }
        public string NodeName { get; set; }

        /*public void Cast(tblNodeEvent node)
        {
            this.Id = node.Id;
            this.EventDefId = node.EventDefId;
            this.NodeId = node.NodeId;
            this.Reason = node.Reason;
            this.T1 = node.T1;
            this.T3 = node.T3;
            this.NodeName = new NodeDao().ViewDetail(Convert.ToInt32(node.NodeId)).Name;
            if (node.T3 != null)
                this.strStartDate = Convert.ToDateTime(node.T3).ToString("yyyy/MM/dd HH:mm:ss");
            if (node.T1 != null)
                this.strFromDate = Convert.ToDateTime(node.T1).ToString("yyyy/MM/dd  HH:mm:ss");

        }*/
        /*public tblNodeEvent Cast()
        {
            return new tblNodeEvent()
            {
                Id = this.Id,
                EventDefId = this.EventDefId,
                NodeId = this.NodeId,
                Reason = this.Reason,
                T1 = this.T1,
                T3 = this.T3
            };
        }*/
    }
}

avani.andon.web/Web/Controllers/NodeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web.Mvc;
using System.Web.Services;
using Model.Dao;
using Model.DataModel;
using avSVAW.Models;

namespace avSVAW.Controllers
{
    public class NodeController : BaseController
    {
        public ActionResult Index(string LineId)
        {
            ViewBag.Factories = new FactoryDao().listAll();
           
            ViewBag.Zones = new ZoneDao().listAll();
            //ViewBag.NodeType = new NodeTypeDao().listAll();
            int iLineId = 0;
            if (!string.IsNullOrEmpty(LineId))
            {
                iLineId = Convert.ToInt32(LineId);
            }
            ViewBag.Lines = new LineDao().listAll();
            ViewBag.Line = LineId;
            List<tblNode> lst = new NodeDao().listAll().Where(p=>p.LineId==iLineId || iLineId==0).OrderBy(x => x.LineId).ThenBy(x => x.nOrder).ToList();
            List<NodeForm> model = new List<NodeForm>();
            foreach(tblNode l in lst)
            {
                NodeForm lf = new NodeForm();
                lf.Cast(l);
                model.Add(lf);
            }
            return View("Index", model);
        }
  
        public ActionResult Create()
        {
            NodeForm model = new NodeForm();
            model.Lines = new LineDao().listAll().Select(n =>
                new SelectListItem
                {
                    Value = n.Id.ToString(),
                    Text = n.Code
                }).ToList();

            //model.Zones = new ZoneDao().listAll().Select(n =>
            //    new SelectListItem
            //    {
            //        Value = n.Id.ToString(),
            //        Text = n.Name
            //    }).ToList();

            //model.NodeTypes = new NodeTypeDao().listAll().Select(n =>
            //    new SelectListItem
            //    {
            //        Value = n.Id.ToString(),
            //        Text = n.Code
            //    }).ToList();

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(NodeForm model)
        {
            if (ModelState.IsValid)
            {
                tblNode l = model.Cast();
                new NodeDao().Insert(l);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int Id)
        {
            tblNode l = new NodeDao().ViewDetail(Id);
            NodeForm model = new NodeForm();
            model.Cast(l);
            model.Lines = new LineDao().listAll().Select(n =>
                   new SelectListItem
                   {
                       Value = n.Id.ToString(),
                       Text = n.Code
                   }).ToList();

            //model.Zones = new ZoneDao().listAll().Select(n =>
            //    new SelectListItem
            //    {
            //        Value = n.Id.ToString(),
            //        Text = n.Name
            //    }).ToList();

            //model.NodeTypes = new NodeTypeDao().listAll().Select(n =>
            //    new SelectListItem
            //    {
            //        Value = n.Id.ToString(),
            //        Text = n.Code
            //    }).ToList();

            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(NodeForm model)
        {
            tblNode l = model.Cast();
            new NodeDao().Update(l);
            // udpate NodeONline
           return RedirectToAction("Index");
        }

        public ActionResult Delete(int Id)
        {
            new NodeDao().Delete(Id);
            return RedirectToAction("Index");
        }


        [WebMethod]
        public JsonResult GetNodeJsonList()
        {
            List<tblNode> lst = new NodeDao().listAll();
            List<NodeForm> model = new List<NodeForm>();
            foreach (tblNode l in lst)
            {
                NodeForm lf = new NodeForm();
                lf.Cast(l);
                model.Add(lf);
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

avani.andon.web/Web/Views/Node/AutoGenerate.cshtml
@using avAndon.Models;

@{
    ViewBag.Title = Resources.Language.Node;
    ViewBag.SubTitle = Resources.Language.AutoGenerate + " " + Resources.Language.Node;
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Menu {
    @Scripts.Render("~/Scripts/Tables/Data/menu")
    @Scripts.Render("~/Scripts/Forms/Advanced/menu")
    @Scripts.Render("~/Scripts/Dictionary/Node-menu.js")
}

@Styles.Render("~/AdminLTE/plugins/daterangepicker/css")
@Styles.Render("~/AdminLTE/plugins/icheck/css")
@Styles.Render("~/AdminLTE/plugins/colorpicker/css")
@Styles.Render("~/AdminLTE/plugins/timepicker/css")
@Styles.Render("~/AdminLTE/plugins/select2/css")
@Styles.Render("~/AdminLTE/dist/css")
@Styles.Render("~/AdminLTE/dist/css/skins")
@Styles.Render("~/AdminLTE/plugins/datatables/css")



    <div class="row">
        <div class="col-xs-12">

            <div class="box">
                <form class="form-horizontal" id="frmDetail" method="post" action="@Url.Action("ActionGenerate")">
                    <div class="box-header">
                        <label for="ZoneName" class="col-sm-2 control-label">@Resources.Language.Factory</label>
                        <div class="col-sm-3">
                            <select class="form-control select2" id="FactoryId" name="FactoryId" style="width: 100%;">
                                @{
                                    int intFactoryId = int.Parse(Request.Params["FactoryId"].ToString());
                                    List<FactoryModels> fList = new List<FactoryModels>();
                                    fList = new FactoryModels().GetList();
                                }
                                @foreach (FactoryModels f in fList)
                                {
                                    string strCheck = "";
                                    if (f.Id == intFactoryId) { strCheck = " selected "; }
                                <option value="@f.Id" @strCheck>@f.Name</option>
                                }
                            </select>
                        </div>

                        <a id="btnLoadMatrix" href="#" class="btn btn-primary">
                            <i class="fa fa-search"></i>&nbsp;&nbsp;@Resources.Language.View &nbsp;
                        </a>

                        <div style="float:right;">
                            <a href="@Url.Action("Index", new { FactoryId = intFactoryId })" class="btn btn-info">
                                <i class="fa fa-mail-reply"></i>&nbsp;&nbsp; @Resources.Language.Back &nbsp;
                            </a>
                        </div>
                    </div>
                    <div class="box-body">
                        @{
                            List<ZoneModels> lstZone = new List<ZoneModels>();
                            lstZone = new ZoneModels().GetList();
                            List<LineModels> lstLine = new List<LineModels>();
                            lstLine = new LineModels().GetList(intFactoryId);
                            int iLine = 1, iZone = 1;
                        }
                        <table id="nodelist" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>&nbsp;</th>
                                    @foreach (ZoneModels z in lstZone)
                                    {
                                        <th>@z.Name</th>
                                    }
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (LineModels l in lstLine)
                                {
                                    <tr>
                                        <td>@l.Name</td>
                                        @for (iZone = 1; iZone <= lstZone.Count; iZone++)
                                        {
                                            <td>
                                                <input type="text" name="txt-@iLine-@iZone" class="form-control" value="" />
                                            </td>
                                        }
                                    </tr>
                                    iLine++;
                                }
                            </tbody>
                        </table>
                        <div class="form-group">
                            <div class="col-sm-12" style="padding-top: 10px;">
                                <input type="checkbox" class="flat-red" name="ContinueValue" checked>
                                <span><b>&nbsp;@Resources.Language.ContinueIncreaseLine</b></span>
                            </div>
                        </div>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>&nbsp;@Resources.Language.AutoGenerate &nbsp;</button>
                        <a href="@Url.Action("Index", new { FactoryId = intFactoryId })" class="btn btn-info pull-right">
                            <i class="fa fa-mail-reply"></i>&nbsp;&nbsp; @Resources.Language.Back &nbsp;
                        </a>
                    </div>
                    <!-- /.box-footer -->
                </form>

</div>

        </div>
    </div>
 @section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/datatables/js")
    @Scripts.Render("~/Scripts/Tables/Data")
    @Scripts.Render("~/AdminLTE/plugins/select2/js")
    @Scripts.Render("~/AdminLTE/plugins/input-mask/js")
    @Scripts.Render("~/AdminLTE/plugins/momentjs/js")
    @Scripts.Render("~/AdminLTE/plugins/daterangepicker/js")
    @Scripts.Render("~/AdminLTE/plugins/colorpicker/js")
    @Scripts.Render("~/AdminLTE/plugins/timepicker/js")
    @Scripts.Render("~/AdminLTE/plugins/icheck/js")
    @Scripts.Render("~/Scripts/Forms/Advanced")
}

avani.andon.web/Web/Views/Node/Create.cshtml
@model avSVAW.Models.NodeForm
@{

    //ViewBag.Title = Resources.Language.Node;
    //ViewBag.SubTitle = Resources.Language.Create + " " + ViewBag.Title;
}
@section header{
    @ViewBag.SubTitle
}
@section Styles{
    <style>

        /* Create a custom checkbox */
        .av-checkbox {
            height: 25px;
            width: 25px;
            /*background-color: #eee;*/
        }
    </style>

}

@section Scripts{
    <script>
        //add css for attach file element
        var input = $("input:file").css({
            width: "100%",
            border: "0.1px solid"
        });
    </script>
    <script src="~/assets/js/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            $('#frmValidate').validate({ // initialize the plugin
                rules: {
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });

            var _atsite = $("#Active").val();
            //alert(_atsite);
            if (_atsite == "True") {
                //alert(_atsite == "value");
                $("#Chk_Active").attr('checked', true);
            }
            $("#Chk_Active").on('change', function (event) {
                var _value = this.checked;
                if (_value) {
                    $("#Active").val('true');
                }
                else {
                    $("#Active").val('false');
                }
            });
        })

    </script>
}

<h3 style="margin-top: -10px;">@Resources.Language.Create @Resources.Language.Node</h3>

<div class="row">
    <div class="col-xs-12">

        <div class="box">
            @using (Html.BeginForm("Create", "Node", FormMethod.Post, new { @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
            {
            <div class="box-body">
                <input type="hidden" name="Id" class="form-control" value="@Model.Id" />
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.Name, Resources.Language.Name, new { @class = "control-label required" })
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", @required = "required" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.nOrder, Resources.Language.Order, new { @class = "control-label" })
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.nOrder, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12", @type = "number", @min = "1", @step = "1" })
                    </div>

                </div>
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.Description, Resources.Language.Description, new { @class = "control-label" })
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>

                </div>
                @*<div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.rId, "R_ID", new { @class = "control-label" })
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.rId, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>

                </div>*@

                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.Active, Resources.Language.Active, new { @class = "control-label required" })
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <input type="checkbox" id="Chk_Active" name="Chk_Active" class="av-checkbox" />
                        @Html.HiddenFor(model => model.Active, new { @class = "form-control col-md-7 col-xs-12" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.LineId, Resources.Language.Line, new { @class = "control-label" })
                    </div>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        @Html.DropDownListFor(model => model.LineId, Model.Lines, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>
                    @Html.ValidationMessageFor(model => model.LineId, "", new { @class = "text-danger" })
                </div>
                <div class="box-footer">
                    <a href="@Url.Action("Index")" class="btn btn-default" style="margin-left:170px;">
                        @Resources.Language.Back
                    </a>
                    <button style="margin-left:0px;" type="submit" class="btn btn-success">@Resources.Language.Save&nbsp;</button>

                </div>
            </div>
            }
        </div>

    </div>
</div>

avani.andon.web/Web/Views/Node/Edit.cshtml
@model avSVAW.Models.NodeForm
@{

    @*ViewBag.Title = Resources.Language.Node;
        ViewBag.SubTitle = Resources.Language.Edit + " " + ViewBag.Title;*@
}

@section Styles{
    <style>

        /* Create a custom checkbox */
        .av-checkbox {
            height: 25px;
            width: 25px;
            /*background-color: #eee;*/
        }
    </style>

}

@section Scripts{
    <script>
        //add css for attach file element
        var input = $("input:file").css({
            width: "100%",
            border: "0.1px solid"
        });
    </script>
    <script src="~/assets/js/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            $('#frmValidate').validate({ // initialize the plugin
                rules: {
                    Name: {
                        required: true
                    },
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });

            var _atsite = $("#Active").val();
            //alert(_atsite);
            if (_atsite == "True") {
                //alert(_atsite == "value");
                $("#Chk_Active").attr('checked', true);
            }
            $("#Chk_Active").on('change', function (event) {
                var _value = this.checked;
                if (_value) {
                    $("#Active").val('true');
                }
                else {
                    $("#Active").val('false');
                }
            });
        })

    </script>
}

<h3 style="margin-top: -10px;">@Resources.Language.Edit @Resources.Language.Node</h3>

<div class="row">
    <div class="col-xs-12">

        <div class="box">
            @using (Html.BeginForm("Edit", "Node", FormMethod.Post, new { @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
            {

            <div class="box-body">

                <input type="hidden" name="Id" class="form-control" value="@Model.Id" />
                @Html.HiddenFor(m => m.ZoneId)
                @Html.HiddenFor(m => m.Active)
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.Name, Resources.Language.Name, new { @class = "control-label required" })
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.nOrder, Resources.Language.Order, new { @class = "control-label" })
                    </div>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.nOrder, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
                @*<div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.rId, "R_ID", new { @class = "control-label" })
                    </div>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.rId, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>*@

                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.LineId, Resources.Language.Line, new { @class = "control-label" })
                    </div>

                    <div class="col-md-2 col-sm-6 col-xs-12">
                        @Html.DropDownListFor(model => model.LineId, Model.Lines, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>
                    @Html.ValidationMessageFor(model => model.LineId, "", new { @class = "text-danger" })

                </div>
                <div class="form-group">
                    <div class="col-sm-2">
                        @Html.LabelFor(model => model.Description, Resources.Language.Description, new { @class = "control-label", @readonly = "true" })
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        @Html.TextBoxFor(model => model.Description, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                    </div>
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>

                @*<div class="form-group">
            <div class="col-sm-2">
                @Html.LabelFor(model => model.ZoneId, Resources.Language.Zone, new { @class = "control-label" })
            </div>
            <div class="col-md-2 col-sm-6 col-xs-12">
                @Html.DropDownListFor(model => model.ZoneId, Model.Zones, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
            </div>
            @Html.ValidationMessageFor(model => model.ZoneId, "", new { @class = "text-danger" })

        </div>*@


                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="@Url.Action("Index")" class="btn btn-default" style="margin-left:170px">
                        @Resources.Language.Back
                    </a>
                    <button type="submit" class="btn btn-success">@Resources.Language.Save&nbsp;</button>

                </div>
                <!-- /.box-footer -->
            </div>
            }

        </div>

    </div>
</div>

avani.andon.web/Web/Views/Node/Index.cshtml
@model List<avSVAW.Models.NodeForm>
@{
    @*ViewBag.Title = Resources.Language.Node;
    ViewBag.SubTitle = Resources.Language.List + " " + ViewBag.Title;*@
}
@section header{
    @ViewBag.SubTitle
}
<h3 style="margin-top: -10px;">@Resources.Language.List @Resources.Language.Node</h3>

<div class="row">
    <div class="col-xs-12">

        <div class="box box-primary">
            <div class="box-header">
                @using (Html.BeginForm("Index", "Node", FormMethod.Get, new { @class = "form-horizontal form-label-left" }))
                {
                    <div class="form-group">
                        <div class="col-sm-1">
                            <label class="control-label">@Resources.Language.Line</label>
                        </div>
                        <div class="col-sm-2">
                            <select id="LineId" name="LineId" class="form-control col-md-7 col-xs-12">
                                <option value="0">@Resources.Language.All</option>
                                @{
                                    var strSelect = "";

                                    for (var iType = 0; iType < ViewBag.Lines.Count; iType++)
                                    {
                                        if (ViewBag.Lines[iType].Id.ToString() == ViewBag.Line)
                                        {
                                            strSelect = " selected ";
                                        }
                                        else
                                        {
                                            strSelect = "";
                                        }
                                        <option value="@ViewBag.Lines[iType].Id" @strSelect> @Html.Raw(HttpUtility.HtmlDecode(@ViewBag.Lines[iType].Name))</option>
                                    }
                                }

                            </select>
                        </div>
                        <div class="col-sm-4">
                            <button type="submit" class="btn btn-success" id=""><i class="fa fa-search"></i>&nbsp;@Resources.Language.Search</button>
                            @*<a href="/Node/Create" class="btn btn-success" id=""><i class="fa fa-plus-circle"></i>&nbsp;@Resources.Language.Create</a>*@
                            &nbsp;
                            &nbsp;
                            &nbsp;
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="box box-primary">
            <div class="box-header">
                <div>
                    <a href="@Url.Action("Create")" class="btn btn-success">
                        <i class="fa fa-plus-circle"></i>&nbsp; @Resources.Language.Create &nbsp;
                    </a>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>@Resources.Language.Name</th>
                            <th>@Resources.Language.Order</th>
                            <th>@Resources.Language.Line</th>
                            @*<th>R_ID</th>*@
                            <th>@Resources.Language.Description</th>
                            <th style="width: 20%;">@Resources.Language.Action</th>
                        </tr>
                    </thead>
                    @if (Model.Count > 0)
                    {
                        var i = 0;
                        <tbody>
                            @foreach (var f in Model)
                            {
                                i = i + 1;
                                <tr>
                                    <td>@i</td>
                                    <td>@f.Name</td>
                                    <td>@f.nOrder</td>
                                    <td>@f.LineName</td>
                                    @*<td style="text-align:center">@f.rId</td>*@
                                    <td>@f.Description</td>
                                    <td>
                                        <a href="/Node/Edit/@f.Id" class="btn btn-primary  btn-xs">
                                            <i class="fa fa-pencil"></i>&nbsp; @Resources.Language.Edit &nbsp;&nbsp;
                                        </a>
                                        <a href="/Node/Delete/@f.Id" class="btn btn-danger btn-xs" onclick="return confirm('@Resources.Language.DeleteConfirm');">
                                            <i class="fa fa-pencil"></i>&nbsp; @Resources.Language.Delete &nbsp;&nbsp;
                                        </a>
                                    </td>
                                </tr>
                            }

                        </tbody>
                    }
                </table>
            </div>
        </div>

    </div>
</div>
@section Scripts {
    @*<script src="~/assets/js/order.js"></script>*@
    <script type="text/javascript">

        $(document).ready(function () {
            $("#CreateNode").click(function () {
                window.location = '/Node/Create';
            });


        });
    </script>
}