avani.andon.web/Web/Controllers/BreakTimeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using Common;
using Model.Dao;
using Model.DataModel;
using avSVAW.Common;
using avSVAW.Models;
using avSVAW.App_Start;

namespace avSVAW.Controllers
{
    public class BreakTimeController : BaseController
    {
        
        // GET: EventDef
        /// <summary>  
        /// First Action method called when page loads  
        /// Fetch all the rows from DB and display it  
        /// </summary>  
        /// <returns>Home View</returns>  
        public ActionResult Index()
        {
            List<tblBreakTime> model = new BreakTimeDao().listAll();
            return View("Index", model);
        }

        /// <summary>  
        /// Action method, called when the "Add New Record" link clicked  
        /// </summary>  
        /// <returns>Create View</returns>  
        public ActionResult Create()
        {
            tblBreakTime model = new tblBreakTime();
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(tblBreakTime model)
        {
            if (ModelState.IsValid)
            {
                new BreakTimeDao().Insert(model);
            }
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int Id)
        {
            tblBreakTime model = new BreakTimeDao().ViewDetail(Id);
            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(tblBreakTime model)
        {
            new BreakTimeDao().Update(model);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int Id)
        {
            new BreakTimeDao().Delete(Id);
            return RedirectToAction("Index");
        }


        [WebMethod]
        public JsonResult GetEventDefJsonList()
        {
            List<tblBreakTime> lst = new BreakTimeDao().listAll();
            return Json(lst);
        }
    }
}

avani.andon.web/Web/Views/BreakTime/Create.cshtml
@model Model.DataModel.tblBreakTime
@{
    //ViewBag.Title = Resources.Language.BreakTime;
    //ViewBag.SubTitle = Resources.Language.Create + " " + ViewBag.Title;
}
@section header{
    @ViewBag.SubTitle
}
<h3 style="margin-top: -10px;">@Resources.Language.Create @Resources.Language.BreakTime</h3>

<div class="row">
    <div class="col-xs-12">

        <div class="box">

            @using (Html.BeginForm("Create", "BreakTime", FormMethod.Post, new { @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="box-body">

                    <input type="hidden" name="Id" class="form-control" value="@Model.Id" />

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Name, Resources.Language.BreakTime, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.StartHour, Resources.Language.Start, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.StartHour, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.StartMinute, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.FinishHour, Resources.Language.Finish, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.FinishHour, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.FinishMinute, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                    </div>

                    <!-- /.box-body -->
                    <div class="form-group">
                        <div class="col-sm-2"></div>
                        <div class="col-sm-6">
                            <a href="@Url.Action("Index")" class="btn btn-default">
                                @Resources.Language.Back
                            </a>
                            <button type="submit" class="btn btn-success">Ghi lại</button>

                        </div>
                    </div>
                    <!-- /.box-footer -->
                </div>
            }

        </div>

    </div>
</div>
@section Scripts {
    @*<script src="~/assets/js/order.js"></script>*@
    <script src="~/assets/js/jquery.validate.js"></script>



    <script type="text/javascript">


        $(document).ready(function () {
            $('#frmValidate').validate({ // initialize the plugin
                rules: {
                    Name: {
                        required: true
                    },
                    StartHour: {
                        required: true,
                        number: true
                    },
                    FinishHour: {
                        required: true,
                        number: true
                    },
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
}

avani.andon.web/Web/Views/BreakTime/Edit.cshtml
@model Model.DataModel.tblBreakTime
@{
    //ViewBag.Title = Resources.Language.BreakTime;
    //ViewBag.SubTitle = Resources.Language.Edit + " " + ViewBag.Title;
}
@section header{
    @ViewBag.SubTitle
}

<h3 style="margin-top: -10px;">@Resources.Language.Edit @Resources.Language.BreakTime</h3>

<div class="row">
    <div class="col-xs-12">

        <div class="box">
            @*<form class="form-horizontal" id="frmDetail" method="post" action="@Url.Action("UpdateRecord")">*@
            @using (Html.BeginForm("Edit", "BreakTime", FormMethod.Post, new { @class = "form-horizontal form-label-left", @id = "frmValidate", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="box-body">

                    <input type="hidden" name="EventDefId" class="form-control" value="@Model.Id" />
                    <input type="hidden" name="Id" class="form-control" value="@Model.Id" />

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.Name, Resources.Language.BreakTime, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.Name, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.StartHour, Resources.Language.Start, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.StartHour, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.StartMinute, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        <div class="col-sm-2">
                            @Html.LabelFor(model => model.FinishHour, Resources.Language.Finish, new { @class = "control-label required" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.FinishHour, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                        <div class="col-md-2 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(model => model.FinishMinute, htmlAttributes: new { @class = "form-control col-md-7 col-xs-12" })
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="form-group">
                        <div class="col-md-2"></div>
                        <div class="col-md-6">
                            <a href="@Url.Action("Index")" class="btn btn-default">
                                @Resources.Language.Back
                            </a>
                            <button type="submit" class="btn btn-success">Ghi lại</button>

                        </div>
                    </div>
                    <!-- /.box-footer -->
                </div>
            }

        </div>

    </div>
</div>

@section Scripts {
    @*<script src="~/assets/js/order.js"></script>*@
    <script src="~/assets/js/jquery.validate.js"></script>



    <script type="text/javascript">


        $(document).ready(function () {
            $('#frmValidate').validate({ // initialize the plugin
                rules: {
                    Name: {
                        required: true
                    },
                    StartHour: {
                        required: true
                    },
                    FinishHour: {
                        required: true
                    },
                },
                submitHandler: function (form) {
                    form.submit();
                }
            });
        });
    </script>
}

avani.andon.web/Web/Views/BreakTime/Index.cshtml
@model List<Model.DataModel.tblBreakTime>
@{
    //ViewBag.Title = Resources.Language.BreakTime;
    //ViewBag.SubTitle = Resources.Language.List + " " + ViewBag.Title;
}
@section header{
    @ViewBag.SubTitle
}

@*@Styles.Render("~/AdminLTE/plugins/datatables/css")*@
<h3 style="margin-top: -10px;">@Resources.Language.List @Resources.Language.BreakTime</h3>

<div class="row">
    <div class="col-xs-12">

        <div class="box">
            <div class="box-header">
                <div>
                    <a href="@Url.Action("Create")" class="btn btn-success">
                        <i class="fa fa-plus-circle"></i>&nbsp; @Resources.Language.Create &nbsp;
                    </a>
                </div>
            </div>
            <div class="box-body">
                <table id="EventDeflist" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>@Resources.Language.Name</th>
                            <th>@Resources.Language.Start</th>
                            <th>@Resources.Language.Finish</th>
                            <th>@Resources.Language.TotalDuration (@Resources.Language.Minute)</th>
                            @*<th style="width: 20%">@Resources.Language.Action</th>*@
                        </tr>
                    </thead>
                    @if (Model.Count > 0)
                    {
                        var iCount = 1;
                        <tbody>
                            @foreach (var ev in Model)
                            {
                                <tr>
                                    <td>@iCount</td>
                                    <td>@ev.Name</td>
                                    <td>@ev.StartHour.ToString("00"):@ev.StartMinute.ToString("00") </td>
                                    <td>@ev.FinishHour.ToString("00"):@ev.FinishMinute.ToString("00") </td>
                                    <td>@ev.TotalMinute</td>

                                    <td>
                                        @*@Html.ActionLink("Edit ", "Edit", new { EventDefID = dr["Id"].ToString() }, new { @class = "btn  btn-primary" })*@
                                        <a href="/BreakTime/Edit/@ev.Id" class="btn btn-primary  btn-xs">
                                            <i class="fa fa-pencil"></i>&nbsp; @Resources.Language.Edit &nbsp;&nbsp;
                                        </a>
                                        &nbsp;
                                        <a href="/BreakTime/Delete/@ev.Id" class="btn btn-danger  btn-xs" onclick="return confirm('@Resources.Language.DeleteConfirm')">
                                            <i class="fa fa-trash"></i> &nbsp;@Resources.Language.Delete&nbsp;&nbsp;
                                        </a>
                                    </td>
                                </tr>
                                iCount++;
                            }
                        </tbody>
                    }

                </table>
            </div>
        </div>

    </div>
</div>
@*@section Scripts {
        @Scripts.Render("~/AdminLTE/plugins/datatables/js")
        @Scripts.Render("~/Scripts/Tables/Data")
    }*@